spring:
  application:
    name: chatbot
  datasource:
    url: jdbc:mysql://localhost:3306/crypto_chatbot
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 5454
